//
// Generated by Bluespec Compiler, version 2011.04.C (build 23804, 2011-04-18)
//
// On Wed Aug  3 12:04:18 EDT 2011
//
// Method conflict info:
// Method: enq_notFull__read
// Conflict-free: enq_notFull__read,
// 	       enq_enq_write,
// 	       deq_notEmpty__read,
// 	       deq_first__read,
// 	       deq_deq__read
//
// Method: enq_enq_write
// Conflict-free: enq_notFull__read,
// 	       deq_notEmpty__read,
// 	       deq_first__read,
// 	       deq_deq__read
// Conflicts: enq_enq_write
//
// Method: deq_notEmpty__read
// Conflict-free: enq_notFull__read,
// 	       enq_enq_write,
// 	       deq_notEmpty__read,
// 	       deq_first__read,
// 	       deq_deq__read
//
// Method: deq_first__read
// Conflict-free: enq_notFull__read,
// 	       enq_enq_write,
// 	       deq_notEmpty__read,
// 	       deq_first__read,
// 	       deq_deq__read
//
// Method: deq_deq__read
// Conflict-free: enq_notFull__read,
// 	       enq_enq_write,
// 	       deq_notEmpty__read,
// 	       deq_first__read
// Conflicts: deq_deq__read
//
//
// Ports:
// Name                         I/O  size props
// enq_notFull_READ               O     1
// deq_notEmpty_READ              O     1
// deq_first_READ                 O    33
// CLK                            I     1 clock
// RST_N                          I     1 reset
// enq_enq_WRITE                  I    33
// enq_enq_EN_WRITE               I     1
// deq_deq_WRITE                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkPcQ(CLK,
	     RST_N,

	     enq_notFull_READ,

	     enq_enq_WRITE,
	     enq_enq_EN_WRITE,

	     deq_notEmpty_READ,

	     deq_first_READ,

	     deq_deq_WRITE);
  input  CLK;
  input  RST_N;

  // value method enq_notFull__read
  output enq_notFull_READ;

  // action method enq_enq_write
  input  [32 : 0] enq_enq_WRITE;
  input  enq_enq_EN_WRITE;

  // value method deq_notEmpty__read
  output deq_notEmpty_READ;

  // value method deq_first__read
  output [32 : 0] deq_first_READ;

  // action method deq_deq__read
  input  deq_deq_WRITE;

  // signals for module outputs
  wire [32 : 0] deq_first_READ;
  wire deq_notEmpty_READ, enq_notFull_READ;

  // ports of submodule mod__head
  wire [1 : 0] mod__head$IN_WRITE, mod__head$OUT_READ;
  wire mod__head$IN_EN_WRITE;

  // ports of submodule mod__mod__deq___deq__data_
  wire mod__mod__deq___deq__data_$IN_EN_WRITE,
       mod__mod__deq___deq__data_$OUT_READ;

  // ports of submodule mod__mod__deq___first___data_
  wire [32 : 0] mod__mod__deq___first___data_$IN_WRITE,
		mod__mod__deq___first___data_$OUT_READ;
  wire mod__mod__deq___first___data_$IN_EN_WRITE;

  // ports of submodule mod__mod__deq___notEmpty___data_
  wire mod__mod__deq___notEmpty___data_$IN_EN_WRITE,
       mod__mod__deq___notEmpty___data_$IN_WRITE,
       mod__mod__deq___notEmpty___data_$OUT_READ;

  // ports of submodule mod__mod__enq___enq__data_
  wire [32 : 0] mod__mod__enq___enq__data_$IN_WRITE,
		mod__mod__enq___enq__data_$OUT_READ;
  wire mod__mod__enq___enq__data_$IN_EN_WRITE;

  // ports of submodule mod__mod__enq___enq__en_
  wire mod__mod__enq___enq__en_$IN_EN_WRITE,
       mod__mod__enq___enq__en_$OUT_READ;

  // ports of submodule mod__mod__enq___notFull___data_
  wire mod__mod__enq___notFull___data_$IN_EN_WRITE,
       mod__mod__enq___notFull___data_$IN_WRITE,
       mod__mod__enq___notFull___data_$OUT_READ;

  // ports of submodule mod__numElems
  wire [1 : 0] mod__numElems$IN_WRITE, mod__numElems$OUT_READ;
  wire mod__numElems$IN_EN_WRITE;

  // ports of submodule mod__regs_mod__mod__read___req__data_
  wire [1 : 0] mod__regs_mod__mod__read___req__data_$IN_WRITE,
	       mod__regs_mod__mod__read___req__data_$OUT_READ;
  wire mod__regs_mod__mod__read___req__data_$IN_EN_WRITE;

  // ports of submodule mod__regs_mod__mod__read___req__en_
  wire mod__regs_mod__mod__read___req__en_$IN_EN_WRITE;

  // ports of submodule mod__regs_mod__mod__read___resp___data_
  wire [32 : 0] mod__regs_mod__mod__read___resp___data_$IN_WRITE,
		mod__regs_mod__mod__read___resp___data_$OUT_READ;
  wire mod__regs_mod__mod__read___resp___data_$IN_EN_WRITE;

  // ports of submodule mod__regs_mod__mod__write___data_
  wire [34 : 0] mod__regs_mod__mod__write___data_$IN_WRITE,
		mod__regs_mod__mod__write___data_$OUT_READ;
  wire mod__regs_mod__mod__write___data_$IN_EN_WRITE;

  // ports of submodule mod__regs_mod__mod__write___en_
  wire mod__regs_mod__mod__write___en_$IN_EN_WRITE,
       mod__regs_mod__mod__write___en_$OUT_READ;

  // ports of submodule mod__regs_mod__rf_mod__read___req__data_
  wire [1 : 0] mod__regs_mod__rf_mod__read___req__data_$IN_WRITE,
	       mod__regs_mod__rf_mod__read___req__data_$OUT_READ;
  wire mod__regs_mod__rf_mod__read___req__data_$IN_EN_WRITE;

  // ports of submodule mod__regs_mod__rf_mod__read___req__en_
  wire mod__regs_mod__rf_mod__read___req__en_$IN_EN_WRITE;

  // ports of submodule mod__regs_mod__rf_mod__read___resp___data_
  wire [32 : 0] mod__regs_mod__rf_mod__read___resp___data_$IN_WRITE,
		mod__regs_mod__rf_mod__read___resp___data_$OUT_READ;
  wire mod__regs_mod__rf_mod__read___resp___data_$IN_EN_WRITE;

  // ports of submodule mod__regs_mod__rf_mod__write___data_
  wire [34 : 0] mod__regs_mod__rf_mod__write___data_$IN_WRITE,
		mod__regs_mod__rf_mod__write___data_$OUT_READ;
  wire mod__regs_mod__rf_mod__write___data_$IN_EN_WRITE;

  // ports of submodule mod__regs_mod__rf_mod__write___en_
  wire mod__regs_mod__rf_mod__write___en_$IN_EN_WRITE,
       mod__regs_mod__rf_mod__write___en_$OUT_READ;

  // ports of submodule mod__regs_mod__rf_rf
  wire [32 : 0] mod__regs_mod__rf_rf$READ_RESP_READ,
		mod__regs_mod__rf_rf$WRITE_DATA_WRITE;
  wire [1 : 0] mod__regs_mod__rf_rf$READ_REQ_WRITE,
	       mod__regs_mod__rf_rf$WRITE_INDEX_WRITE;
  wire mod__regs_mod__rf_rf$WRITE_EN_WRITE;

  // ports of submodule mod__regs_mod__whichReg
  wire mod__regs_mod__whichReg$IN_EN_WRITE;

  // ports of submodule mod__tail
  wire [1 : 0] mod__tail$IN_WRITE, mod__tail$OUT_READ;
  wire mod__tail$IN_EN_WRITE;

  // remaining internal signals
  wire [1 : 0] y__h3745, y__h3747, y__h4950, y__h4952;

  // value method enq_notFull__read
  assign enq_notFull_READ = mod__mod__enq___notFull___data_$OUT_READ ;

  // value method deq_notEmpty__read
  assign deq_notEmpty_READ = mod__mod__deq___notEmpty___data_$OUT_READ ;

  // value method deq_first__read
  assign deq_first_READ = mod__mod__deq___first___data_$OUT_READ ;

  // submodule mod__head
  mkReg #( /*width*/ 32'd2,  /*init*/ 2'd0) mod__head(.CLK(CLK),
						      .RST_N(RST_N),
						      .IN_WRITE(mod__head$IN_WRITE),
						      .IN_EN_WRITE(mod__head$IN_EN_WRITE),
						      .OUT_READ(mod__head$OUT_READ));

  // submodule mod__mod__deq___deq__data_
  mkPulse mod__mod__deq___deq__data_(.IN_EN_WRITE(mod__mod__deq___deq__data_$IN_EN_WRITE),
				     .OUT_READ(mod__mod__deq___deq__data_$OUT_READ));

  // submodule mod__mod__deq___first___data_
  mkWire #( /*width*/ 32'd33) mod__mod__deq___first___data_(.IN_WRITE(mod__mod__deq___first___data_$IN_WRITE),
							    .IN_EN_WRITE(mod__mod__deq___first___data_$IN_EN_WRITE),
							    .OUT_READ(mod__mod__deq___first___data_$OUT_READ));

  // submodule mod__mod__deq___notEmpty___data_
  mkWire #( /*width*/ 32'd1) mod__mod__deq___notEmpty___data_(.IN_WRITE(mod__mod__deq___notEmpty___data_$IN_WRITE),
							      .IN_EN_WRITE(mod__mod__deq___notEmpty___data_$IN_EN_WRITE),
							      .OUT_READ(mod__mod__deq___notEmpty___data_$OUT_READ));

  // submodule mod__mod__enq___enq__data_
  mkWire #( /*width*/ 32'd33) mod__mod__enq___enq__data_(.IN_WRITE(mod__mod__enq___enq__data_$IN_WRITE),
							 .IN_EN_WRITE(mod__mod__enq___enq__data_$IN_EN_WRITE),
							 .OUT_READ(mod__mod__enq___enq__data_$OUT_READ));

  // submodule mod__mod__enq___enq__en_
  mkPulse mod__mod__enq___enq__en_(.IN_EN_WRITE(mod__mod__enq___enq__en_$IN_EN_WRITE),
				   .OUT_READ(mod__mod__enq___enq__en_$OUT_READ));

  // submodule mod__mod__enq___notFull___data_
  mkWire #( /*width*/ 32'd1) mod__mod__enq___notFull___data_(.IN_WRITE(mod__mod__enq___notFull___data_$IN_WRITE),
							     .IN_EN_WRITE(mod__mod__enq___notFull___data_$IN_EN_WRITE),
							     .OUT_READ(mod__mod__enq___notFull___data_$OUT_READ));

  // submodule mod__numElems
  mkReg #( /*width*/ 32'd2,  /*init*/ 2'd0) mod__numElems(.CLK(CLK),
							  .RST_N(RST_N),
							  .IN_WRITE(mod__numElems$IN_WRITE),
							  .IN_EN_WRITE(mod__numElems$IN_EN_WRITE),
							  .OUT_READ(mod__numElems$OUT_READ));

  // submodule mod__regs_mod__mod__read___req__data_
  mkWire #( /*width*/ 32'd2) mod__regs_mod__mod__read___req__data_(.IN_WRITE(mod__regs_mod__mod__read___req__data_$IN_WRITE),
								   .IN_EN_WRITE(mod__regs_mod__mod__read___req__data_$IN_EN_WRITE),
								   .OUT_READ(mod__regs_mod__mod__read___req__data_$OUT_READ));

  // submodule mod__regs_mod__mod__read___req__en_
  mkPulse mod__regs_mod__mod__read___req__en_(.IN_EN_WRITE(mod__regs_mod__mod__read___req__en_$IN_EN_WRITE),
					      .OUT_READ());

  // submodule mod__regs_mod__mod__read___resp___data_
  mkWire #( /*width*/ 32'd33) mod__regs_mod__mod__read___resp___data_(.IN_WRITE(mod__regs_mod__mod__read___resp___data_$IN_WRITE),
								      .IN_EN_WRITE(mod__regs_mod__mod__read___resp___data_$IN_EN_WRITE),
								      .OUT_READ(mod__regs_mod__mod__read___resp___data_$OUT_READ));

  // submodule mod__regs_mod__mod__write___data_
  mkWire #( /*width*/ 32'd35) mod__regs_mod__mod__write___data_(.IN_WRITE(mod__regs_mod__mod__write___data_$IN_WRITE),
								.IN_EN_WRITE(mod__regs_mod__mod__write___data_$IN_EN_WRITE),
								.OUT_READ(mod__regs_mod__mod__write___data_$OUT_READ));

  // submodule mod__regs_mod__mod__write___en_
  mkPulse mod__regs_mod__mod__write___en_(.IN_EN_WRITE(mod__regs_mod__mod__write___en_$IN_EN_WRITE),
					  .OUT_READ(mod__regs_mod__mod__write___en_$OUT_READ));

  // submodule mod__regs_mod__rf_mod__read___req__data_
  mkWire #( /*width*/ 32'd2) mod__regs_mod__rf_mod__read___req__data_(.IN_WRITE(mod__regs_mod__rf_mod__read___req__data_$IN_WRITE),
								      .IN_EN_WRITE(mod__regs_mod__rf_mod__read___req__data_$IN_EN_WRITE),
								      .OUT_READ(mod__regs_mod__rf_mod__read___req__data_$OUT_READ));

  // submodule mod__regs_mod__rf_mod__read___req__en_
  mkPulse mod__regs_mod__rf_mod__read___req__en_(.IN_EN_WRITE(mod__regs_mod__rf_mod__read___req__en_$IN_EN_WRITE),
						 .OUT_READ());

  // submodule mod__regs_mod__rf_mod__read___resp___data_
  mkWire #( /*width*/ 32'd33) mod__regs_mod__rf_mod__read___resp___data_(.IN_WRITE(mod__regs_mod__rf_mod__read___resp___data_$IN_WRITE),
									 .IN_EN_WRITE(mod__regs_mod__rf_mod__read___resp___data_$IN_EN_WRITE),
									 .OUT_READ(mod__regs_mod__rf_mod__read___resp___data_$OUT_READ));

  // submodule mod__regs_mod__rf_mod__write___data_
  mkWire #( /*width*/ 32'd35) mod__regs_mod__rf_mod__write___data_(.IN_WRITE(mod__regs_mod__rf_mod__write___data_$IN_WRITE),
								   .IN_EN_WRITE(mod__regs_mod__rf_mod__write___data_$IN_EN_WRITE),
								   .OUT_READ(mod__regs_mod__rf_mod__write___data_$OUT_READ));

  // submodule mod__regs_mod__rf_mod__write___en_
  mkPulse mod__regs_mod__rf_mod__write___en_(.IN_EN_WRITE(mod__regs_mod__rf_mod__write___en_$IN_EN_WRITE),
					     .OUT_READ(mod__regs_mod__rf_mod__write___en_$OUT_READ));

  // submodule mod__regs_mod__rf_rf
  mkRegFileLoad_ #( /*width*/ 32'd33,
		    /*n*/ 32'd2,
		    /*size*/ 32'd3,
		    /*file*/ "",
		    /*mode*/ 32'd0) mod__regs_mod__rf_rf(.CLK(CLK),
							 .RST_N(RST_N),
							 .READ_REQ_WRITE(mod__regs_mod__rf_rf$READ_REQ_WRITE),
							 .WRITE_DATA_WRITE(mod__regs_mod__rf_rf$WRITE_DATA_WRITE),
							 .WRITE_INDEX_WRITE(mod__regs_mod__rf_rf$WRITE_INDEX_WRITE),
							 .WRITE_EN_WRITE(mod__regs_mod__rf_rf$WRITE_EN_WRITE),
							 .READ_RESP_READ(mod__regs_mod__rf_rf$READ_RESP_READ));

  // submodule mod__regs_mod__whichReg
  mkReg #( /*width*/ 32'd1) mod__regs_mod__whichReg(.CLK(CLK),
						    .RST_N(RST_N),
						    .IN_EN_WRITE(mod__regs_mod__whichReg$IN_EN_WRITE));

  // submodule mod__tail
  mkReg #( /*width*/ 32'd2,  /*init*/ 2'd0) mod__tail(.CLK(CLK),
						      .RST_N(RST_N),
						      .IN_WRITE(mod__tail$IN_WRITE),
						      .IN_EN_WRITE(mod__tail$IN_EN_WRITE),
						      .OUT_READ(mod__tail$OUT_READ));

  // submodule mod__head
  assign mod__head$IN_WRITE =
	     (mod__head$OUT_READ == 2'd2) ?
	       2'd1 - y__h4950 :
	       mod__head$OUT_READ + 2'd1 ;
  assign mod__head$IN_EN_WRITE = mod__mod__enq___enq__en_$OUT_READ ;

  // submodule mod__mod__deq___deq__data_
  assign mod__mod__deq___deq__data_$IN_EN_WRITE = deq_deq_WRITE ;

  // submodule mod__mod__deq___first___data_
  assign mod__mod__deq___first___data_$IN_WRITE =
	     mod__regs_mod__mod__read___resp___data_$OUT_READ ;
  assign mod__mod__deq___first___data_$IN_EN_WRITE = 1'd1 ;

  // submodule mod__mod__deq___notEmpty___data_
  assign mod__mod__deq___notEmpty___data_$IN_WRITE =
	     mod__numElems$OUT_READ != 2'd0 ;
  assign mod__mod__deq___notEmpty___data_$IN_EN_WRITE = 1'd1 ;

  // submodule mod__mod__enq___enq__data_
  assign mod__mod__enq___enq__data_$IN_WRITE = enq_enq_WRITE ;
  assign mod__mod__enq___enq__data_$IN_EN_WRITE = enq_enq_EN_WRITE ;

  // submodule mod__mod__enq___enq__en_
  assign mod__mod__enq___enq__en_$IN_EN_WRITE = enq_enq_EN_WRITE ;

  // submodule mod__mod__enq___notFull___data_
  assign mod__mod__enq___notFull___data_$IN_WRITE =
	     mod__numElems$OUT_READ != 2'd3 ||
	     mod__mod__deq___deq__data_$OUT_READ ;
  assign mod__mod__enq___notFull___data_$IN_EN_WRITE = 1'd1 ;

  // submodule mod__numElems
  assign mod__numElems$IN_WRITE =
	     mod__numElems$OUT_READ +
	     ({ 1'd0, mod__mod__enq___enq__en_$OUT_READ } -
	      { 1'd0, mod__mod__deq___deq__data_$OUT_READ }) ;
  assign mod__numElems$IN_EN_WRITE = 1'd1 ;

  // submodule mod__regs_mod__mod__read___req__data_
  assign mod__regs_mod__mod__read___req__data_$IN_WRITE = mod__tail$OUT_READ ;
  assign mod__regs_mod__mod__read___req__data_$IN_EN_WRITE = 1'd1 ;

  // submodule mod__regs_mod__mod__read___req__en_
  assign mod__regs_mod__mod__read___req__en_$IN_EN_WRITE = 1'd1 ;

  // submodule mod__regs_mod__mod__read___resp___data_
  assign mod__regs_mod__mod__read___resp___data_$IN_WRITE =
	     mod__regs_mod__rf_mod__read___resp___data_$OUT_READ ;
  assign mod__regs_mod__mod__read___resp___data_$IN_EN_WRITE = 1'd1 ;

  // submodule mod__regs_mod__mod__write___data_
  assign mod__regs_mod__mod__write___data_$IN_WRITE =
	     { mod__head$OUT_READ, mod__mod__enq___enq__data_$OUT_READ } ;
  assign mod__regs_mod__mod__write___data_$IN_EN_WRITE =
	     mod__mod__enq___enq__en_$OUT_READ ;

  // submodule mod__regs_mod__mod__write___en_
  assign mod__regs_mod__mod__write___en_$IN_EN_WRITE =
	     mod__mod__enq___enq__en_$OUT_READ ;

  // submodule mod__regs_mod__rf_mod__read___req__data_
  assign mod__regs_mod__rf_mod__read___req__data_$IN_WRITE =
	     mod__regs_mod__mod__read___req__data_$OUT_READ ;
  assign mod__regs_mod__rf_mod__read___req__data_$IN_EN_WRITE = 1'd1 ;

  // submodule mod__regs_mod__rf_mod__read___req__en_
  assign mod__regs_mod__rf_mod__read___req__en_$IN_EN_WRITE = 1'd1 ;

  // submodule mod__regs_mod__rf_mod__read___resp___data_
  assign mod__regs_mod__rf_mod__read___resp___data_$IN_WRITE =
	     mod__regs_mod__rf_rf$READ_RESP_READ ;
  assign mod__regs_mod__rf_mod__read___resp___data_$IN_EN_WRITE = 1'd1 ;

  // submodule mod__regs_mod__rf_mod__write___data_
  assign mod__regs_mod__rf_mod__write___data_$IN_WRITE =
	     mod__regs_mod__mod__write___data_$OUT_READ ;
  assign mod__regs_mod__rf_mod__write___data_$IN_EN_WRITE =
	     mod__regs_mod__mod__write___en_$OUT_READ ;

  // submodule mod__regs_mod__rf_mod__write___en_
  assign mod__regs_mod__rf_mod__write___en_$IN_EN_WRITE =
	     mod__regs_mod__mod__write___en_$OUT_READ ;

  // submodule mod__regs_mod__rf_rf
  assign mod__regs_mod__rf_rf$READ_REQ_WRITE =
	     mod__regs_mod__rf_mod__read___req__data_$OUT_READ ;
  assign mod__regs_mod__rf_rf$WRITE_DATA_WRITE =
	     mod__regs_mod__rf_mod__write___data_$OUT_READ[32:0] ;
  assign mod__regs_mod__rf_rf$WRITE_INDEX_WRITE =
	     mod__regs_mod__rf_mod__write___data_$OUT_READ[34:33] ;
  assign mod__regs_mod__rf_rf$WRITE_EN_WRITE =
	     mod__regs_mod__rf_mod__write___en_$OUT_READ ;

  // submodule mod__regs_mod__whichReg
  assign mod__regs_mod__whichReg$IN_EN_WRITE = 1'd1 ;

  // submodule mod__tail
  assign mod__tail$IN_WRITE =
	     (mod__tail$OUT_READ == 2'd2) ?
	       2'd1 - y__h3745 :
	       mod__tail$OUT_READ + 2'd1 ;
  assign mod__tail$IN_EN_WRITE = mod__mod__deq___deq__data_$OUT_READ ;

  // remaining internal signals
  assign y__h3745 = 2'd2 - y__h3747 ;
  assign y__h3747 = mod__tail$OUT_READ - 2'd1 ;
  assign y__h4950 = 2'd2 - y__h4952 ;
  assign y__h4952 = mod__head$OUT_READ - 2'd1 ;
endmodule  // mkPcQ

