//
// Generated by Bluespec Compiler, version 2011.04.C (build 23804, 2011-04-18)
//
// On Wed Aug  3 11:59:23 EDT 2011
//
// Method conflict info:
// (none)
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkTest(CLK,
	      RST_N);
  input  CLK;
  input  RST_N;

  // ports of submodule x
  wire [31 : 0] x$IN_WRITE, x$OUT_READ;
  wire x$IN_EN_WRITE;

  // ports of submodule y
  wire [31 : 0] y$IN_WRITE, y$OUT_READ;
  wire y$IN_EN_WRITE;

  // submodule x
  mkReg #( /*width*/ 32'd32,  /*init*/ 32'd24) x(.CLK(CLK),
						 .RST_N(RST_N),
						 .IN_WRITE(x$IN_WRITE),
						 .IN_EN_WRITE(x$IN_EN_WRITE),
						 .OUT_READ(x$OUT_READ));

  // submodule y
  mkReg #( /*width*/ 32'd32,  /*init*/ 32'd45) y(.CLK(CLK),
						 .RST_N(RST_N),
						 .IN_WRITE(y$IN_WRITE),
						 .IN_EN_WRITE(y$IN_EN_WRITE),
						 .OUT_READ(y$OUT_READ));

  // submodule x
  assign x$IN_WRITE = y$OUT_READ ;
  assign x$IN_EN_WRITE = 1'd1 ;

  // submodule y
  assign y$IN_WRITE = x$OUT_READ ;
  assign y$IN_EN_WRITE = 1'd1 ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N) $display("%d %d", x$OUT_READ, y$OUT_READ);
  end
  // synopsys translate_on
endmodule  // mkTest

